
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TIMES = 17;
  public static final int EXIT = 13;
  public static final int IDENT = 10;
  public static final int DEVIDE = 18;
  public static final int PLUS = 15;
  public static final int LOOP = 14;
  public static final int COMMANDS = 7;
  public static final int WhiteSpace = 11;
  public static final int Semicolon = 12;
  public static final int EQUALS = 5;
  public static final int EOF = 0;
  public static final int STEP = 6;
  public static final int MINUS = 16;
  public static final int error = 1;
  public static final int INTEGER = 8;
  public static final int FOR = 2;
  public static final int TO = 4;
  public static final int ENDFOR = 9;
  public static final int NEXT = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FOR",
  "NEXT",
  "TO",
  "EQUALS",
  "STEP",
  "COMMANDS",
  "INTEGER",
  "ENDFOR",
  "IDENT",
  "WhiteSpace",
  "Semicolon",
  "EXIT",
  "LOOP",
  "PLUS",
  "MINUS",
  "TIMES",
  "DEVIDE"
  };
}

